### ISSUE TITLE
Simple display of hardcoded HTML

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/CERES-BB-Modules#1]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour
**Description** *what the issue is about*
As a first step toward building BB modules, take the example here and have it just display some hardcoded HTML from the module.

Start with the `ceres_simple` module and copy/modify that. Note to prefix all modules with `ceres_`

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by aad3sh** [comment]
sent a PR for this
